# Generated by Django 6.1 on 2026-09-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_citizen_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['master_citizen_id'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_reference', models.CharField(max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=150)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_identities', to='departments.department')),
                ('master_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_identities', to='interoperability.mastercitizen')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(default='Verified profile match', max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='interoperability.departmentidentity')),
                ('master_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_mappings', to='interoperability.mastercitizen')),
            ],
        ),
        migrations.AddConstraint(
            model_name='departmentidentity',
            constraint=models.UniqueConstraint(fields=('department', 'department_reference'), name='unique_department_reference'),
        ),
    ]
