# Generated by Django 6.1 on 2026-09-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('SCHOLARSHIP', 'Scholarship'), ('VERIFICATION', 'Verification'), ('BENEFIT', 'Benefit'), ('ASSISTANCE', 'Assistance')], max_length=30)),
                ('eligibility', models.TextField(blank=True)),
                ('required_information', models.JSONField(blank=True, default=list)),
                ('processing_stages', models.JSONField(blank=True, default=list)),
                ('estimated_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_simulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='departments.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
    ]
